__asm__(
".global " START " \n"
".type " START ",%function \n"
START ": \n"
"	mov fp, #0 \n"
"	mov lr, #0 \n"
"	mov a1, sp \n"
"	ldr a2, 1f \n"
"2:	add a2, pc, a2 \n"
"	and sp, sp, #-16 \n"
"	bl " START "_c \n"
".weak _DYNAMIC \n"
".hidden _DYNAMIC \n"
"1:	.word _DYNAMIC-2b-8 \n"
);
