#define _BSD_SOURCE
#include <unistd.h>
#include "syscall.h"
#include <stdarg.h>
#include <stdio.h>

#undef syscall

long syscall(long n, ...)
{
	va_list ap;
	syscall_arg_t a,b,c,d,e,f;
	va_start(ap, n);
	a=va_arg(ap, syscall_arg_t);
	b=va_arg(ap, syscall_arg_t);
	c=va_arg(ap, syscall_arg_t);
	d=va_arg(ap, syscall_arg_t);
	e=va_arg(ap, syscall_arg_t);
	f=va_arg(ap, syscall_arg_t);
	va_end(ap);
	return __syscall_ret(__syscall(n,a,b,c,d,e,f));
}

#define UK_VDSO_SYSCALL_MAX 450

void* uk_vdso_syscall_tabel[UK_VDSO_SYSCALL_MAX] = {};

static const char* uk_vdso_syscall_name[UK_VDSO_SYSCALL_MAX] = {
	[0] = "uk_vdso_syscall_read",
	[1] = "uk_vdso_syscall_write",
	[2] = "uk_vdso_syscall_open",
	[3] = "uk_vdso_syscall_close",
	[4] = "uk_vdso_syscall_stat",
	[5] = "uk_vdso_syscall_fstat",
	[6] = "uk_vdso_syscall_lstat",
	[7] = "uk_vdso_syscall_poll",
	[8] = "uk_vdso_syscall_lseek",
	[9] = "uk_vdso_syscall_mmap",
	[10] = "uk_vdso_syscall_mprotect",
	[11] = "uk_vdso_syscall_munmap",
	[12] = "uk_vdso_syscall_brk",
	[13] = "uk_vdso_syscall_rt_sigaction",
	[14] = "uk_vdso_syscall_rt_sigprocmask",
	[15] = "uk_vdso_syscall_rt_sigreturn",
	[16] = "uk_vdso_syscall_ioctl",
	[17] = "uk_vdso_syscall_pread64",
	[18] = "uk_vdso_syscall_pwrite64",
	[19] = "uk_vdso_syscall_readv",
	[20] = "uk_vdso_syscall_writev",
	[21] = "uk_vdso_syscall_access",
	[22] = "uk_vdso_syscall_pipe",
	[23] = "uk_vdso_syscall_select",
	[24] = "uk_vdso_syscall_sched_yield",
	[25] = "uk_vdso_syscall_mremap",
	[26] = "uk_vdso_syscall_msync",
	[27] = "uk_vdso_syscall_mincore",
	[28] = "uk_vdso_syscall_madvise",
	[29] = "uk_vdso_syscall_shmget",
	[30] = "uk_vdso_syscall_shmat",
	[31] = "uk_vdso_syscall_shmctl",
	[32] = "uk_vdso_syscall_dup",
	[33] = "uk_vdso_syscall_dup2",
	[34] = "uk_vdso_syscall_pause",
	[35] = "uk_vdso_syscall_nanosleep",
	[36] = "uk_vdso_syscall_getitimer",
	[37] = "uk_vdso_syscall_alarm",
	[38] = "uk_vdso_syscall_setitimer",
	[39] = "uk_vdso_syscall_getpid",
	[40] = "uk_vdso_syscall_sendfile",
	[41] = "uk_vdso_syscall_socket",
	[42] = "uk_vdso_syscall_connect",
	[43] = "uk_vdso_syscall_accept",
	[44] = "uk_vdso_syscall_sendto",
	[45] = "uk_vdso_syscall_recvfrom",
	[46] = "uk_vdso_syscall_sendmsg",
	[47] = "uk_vdso_syscall_recvmsg",
	[48] = "uk_vdso_syscall_shutdown",
	[49] = "uk_vdso_syscall_bind",
	[50] = "uk_vdso_syscall_listen",
	[51] = "uk_vdso_syscall_getsockname",
	[52] = "uk_vdso_syscall_getpeername",
	[53] = "uk_vdso_syscall_socketpair",
	[54] = "uk_vdso_syscall_setsockopt",
	[55] = "uk_vdso_syscall_getsockopt",
	[56] = "uk_vdso_syscall_clone",
	[57] = "uk_vdso_syscall_fork",
	[58] = "uk_vdso_syscall_vfork",
	[59] = "uk_vdso_syscall_execve",
	[60] = "uk_vdso_syscall_exit",
	[61] = "uk_vdso_syscall_wait4",
	[62] = "uk_vdso_syscall_kill",
	[63] = "uk_vdso_syscall_uname",
	[64] = "uk_vdso_syscall_semget",
	[65] = "uk_vdso_syscall_semop",
	[66] = "uk_vdso_syscall_semctl",
	[67] = "uk_vdso_syscall_shmdt",
	[68] = "uk_vdso_syscall_msgget",
	[69] = "uk_vdso_syscall_msgsnd",
	[70] = "uk_vdso_syscall_msgrcv",
	[71] = "uk_vdso_syscall_msgctl",
	[72] = "uk_vdso_syscall_fcntl",
	[73] = "uk_vdso_syscall_flock",
	[74] = "uk_vdso_syscall_fsync",
	[75] = "uk_vdso_syscall_fdatasync",
	[76] = "uk_vdso_syscall_truncate",
	[77] = "uk_vdso_syscall_ftruncate",
	[78] = "uk_vdso_syscall_getdents",
	[79] = "uk_vdso_syscall_getcwd",
	[80] = "uk_vdso_syscall_chdir",
	[81] = "uk_vdso_syscall_fchdir",
	[82] = "uk_vdso_syscall_rename",
	[83] = "uk_vdso_syscall_mkdir",
	[84] = "uk_vdso_syscall_rmdir",
	[85] = "uk_vdso_syscall_creat",
	[86] = "uk_vdso_syscall_link",
	[87] = "uk_vdso_syscall_unlink",
	[88] = "uk_vdso_syscall_symlink",
	[89] = "uk_vdso_syscall_readlink",
	[90] = "uk_vdso_syscall_chmod",
	[91] = "uk_vdso_syscall_fchmod",
	[92] = "uk_vdso_syscall_chown",
	[93] = "uk_vdso_syscall_fchown",
	[94] = "uk_vdso_syscall_lchown",
	[95] = "uk_vdso_syscall_umask",
	[96] = "uk_vdso_syscall_gettimeofday",
	[97] = "uk_vdso_syscall_getrlimit",
	[98] = "uk_vdso_syscall_getrusage",
	[99] = "uk_vdso_syscall_sysinfo",
	[100] = "uk_vdso_syscall_times",
	[101] = "uk_vdso_syscall_ptrace",
	[102] = "uk_vdso_syscall_getuid",
	[103] = "uk_vdso_syscall_syslog",
	[104] = "uk_vdso_syscall_getgid",
	[105] = "uk_vdso_syscall_setuid",
	[106] = "uk_vdso_syscall_setgid",
	[107] = "uk_vdso_syscall_geteuid",
	[108] = "uk_vdso_syscall_getegid",
	[109] = "uk_vdso_syscall_setpgid",
	[110] = "uk_vdso_syscall_getppid",
	[111] = "uk_vdso_syscall_getpgrp",
	[112] = "uk_vdso_syscall_setsid",
	[113] = "uk_vdso_syscall_setreuid",
	[114] = "uk_vdso_syscall_setregid",
	[115] = "uk_vdso_syscall_getgroups",
	[116] = "uk_vdso_syscall_setgroups",
	[117] = "uk_vdso_syscall_setresuid",
	[118] = "uk_vdso_syscall_getresuid",
	[119] = "uk_vdso_syscall_setresgid",
	[120] = "uk_vdso_syscall_getresgid",
	[121] = "uk_vdso_syscall_getpgid",
	[122] = "uk_vdso_syscall_setfsuid",
	[123] = "uk_vdso_syscall_setfsgid",
	[124] = "uk_vdso_syscall_getsid",
	[125] = "uk_vdso_syscall_capget",
	[126] = "uk_vdso_syscall_capset",
	[127] = "uk_vdso_syscall_rt_sigpending",
	[128] = "uk_vdso_syscall_rt_sigtimedwait",
	[129] = "uk_vdso_syscall_rt_sigqueueinfo",
	[130] = "uk_vdso_syscall_rt_sigsuspend",
	[131] = "uk_vdso_syscall_sigaltstack",
	[132] = "uk_vdso_syscall_utime",
	[133] = "uk_vdso_syscall_mknod",
	[134] = "uk_vdso_syscall_uselib",
	[135] = "uk_vdso_syscall_personality",
	[136] = "uk_vdso_syscall_ustat",
	[137] = "uk_vdso_syscall_statfs",
	[138] = "uk_vdso_syscall_fstatfs",
	[139] = "uk_vdso_syscall_sysfs",
	[140] = "uk_vdso_syscall_getpriority",
	[141] = "uk_vdso_syscall_setpriority",
	[142] = "uk_vdso_syscall_sched_setparam",
	[143] = "uk_vdso_syscall_sched_getparam",
	[144] = "uk_vdso_syscall_sched_setscheduler",
	[145] = "uk_vdso_syscall_sched_getscheduler",
	[146] = "uk_vdso_syscall_sched_get_priority_max",
	[147] = "uk_vdso_syscall_sched_get_priority_min",
	[148] = "uk_vdso_syscall_sched_rr_get_interval",
	[149] = "uk_vdso_syscall_mlock",
	[150] = "uk_vdso_syscall_munlock",
	[151] = "uk_vdso_syscall_mlockall",
	[152] = "uk_vdso_syscall_munlockall",
	[153] = "uk_vdso_syscall_vhangup",
	[154] = "uk_vdso_syscall_modify_ldt",
	[155] = "uk_vdso_syscall_pivot_root",
	[156] = "uk_vdso_syscall__sysctl",
	[157] = "uk_vdso_syscall_prctl",
	[158] = "uk_vdso_syscall_arch_prctl",
	[159] = "uk_vdso_syscall_adjtimex",
	[160] = "uk_vdso_syscall_setrlimit",
	[161] = "uk_vdso_syscall_chroot",
	[162] = "uk_vdso_syscall_sync",
	[163] = "uk_vdso_syscall_acct",
	[164] = "uk_vdso_syscall_settimeofday",
	[165] = "uk_vdso_syscall_mount",
	[166] = "uk_vdso_syscall_umount2",
	[167] = "uk_vdso_syscall_swapon",
	[168] = "uk_vdso_syscall_swapoff",
	[169] = "uk_vdso_syscall_reboot",
	[170] = "uk_vdso_syscall_sethostname",
	[171] = "uk_vdso_syscall_setdomainname",
	[172] = "uk_vdso_syscall_iopl",
	[173] = "uk_vdso_syscall_ioperm",
	[174] = "uk_vdso_syscall_create_module",
	[175] = "uk_vdso_syscall_init_module",
	[176] = "uk_vdso_syscall_delete_module",
	[177] = "uk_vdso_syscall_get_kernel_syms",
	[178] = "uk_vdso_syscall_query_module",
	[179] = "uk_vdso_syscall_quotactl",
	[180] = "uk_vdso_syscall_nfsservctl",
	[181] = "uk_vdso_syscall_getpmsg",
	[182] = "uk_vdso_syscall_putpmsg",
	[183] = "uk_vdso_syscall_afs_syscall",
	[184] = "uk_vdso_syscall_tuxcall",
	[185] = "uk_vdso_syscall_security",
	[186] = "uk_vdso_syscall_gettid",
	[187] = "uk_vdso_syscall_readahead",
	[188] = "uk_vdso_syscall_setxattr",
	[189] = "uk_vdso_syscall_lsetxattr",
	[190] = "uk_vdso_syscall_fsetxattr",
	[191] = "uk_vdso_syscall_getxattr",
	[192] = "uk_vdso_syscall_lgetxattr",
	[193] = "uk_vdso_syscall_fgetxattr",
	[194] = "uk_vdso_syscall_listxattr",
	[195] = "uk_vdso_syscall_llistxattr",
	[196] = "uk_vdso_syscall_flistxattr",
	[197] = "uk_vdso_syscall_removexattr",
	[198] = "uk_vdso_syscall_lremovexattr",
	[199] = "uk_vdso_syscall_fremovexattr",
	[200] = "uk_vdso_syscall_tkill",
	[201] = "uk_vdso_syscall_time",
	[202] = "uk_vdso_syscall_futex",
	[203] = "uk_vdso_syscall_sched_setaffinity",
	[204] = "uk_vdso_syscall_sched_getaffinity",
	[205] = "uk_vdso_syscall_set_thread_area",
	[206] = "uk_vdso_syscall_io_setup",
	[207] = "uk_vdso_syscall_io_destroy",
	[208] = "uk_vdso_syscall_io_getevents",
	[209] = "uk_vdso_syscall_io_submit",
	[210] = "uk_vdso_syscall_io_cancel",
	[211] = "uk_vdso_syscall_get_thread_area",
	[212] = "uk_vdso_syscall_lookup_dcookie",
	[213] = "uk_vdso_syscall_epoll_create",
	[214] = "uk_vdso_syscall_epoll_ctl_old",
	[215] = "uk_vdso_syscall_epoll_wait_old",
	[216] = "uk_vdso_syscall_remap_file_pages",
	[217] = "uk_vdso_syscall_getdents64",
	[218] = "uk_vdso_syscall_set_tid_address",
	[219] = "uk_vdso_syscall_restart_syscall",
	[220] = "uk_vdso_syscall_semtimedop",
	[221] = "uk_vdso_syscall_fadvise64",
	[222] = "uk_vdso_syscall_timer_create",
	[223] = "uk_vdso_syscall_timer_settime",
	[224] = "uk_vdso_syscall_timer_gettime",
	[225] = "uk_vdso_syscall_timer_getoverrun",
	[226] = "uk_vdso_syscall_timer_delete",
	[227] = "uk_vdso_syscall_clock_settime",
	[228] = "uk_vdso_syscall_clock_gettime",
	[229] = "uk_vdso_syscall_clock_getres",
	[230] = "uk_vdso_syscall_clock_nanosleep",
	[231] = "uk_vdso_syscall_exit_group",
	[232] = "uk_vdso_syscall_epoll_wait",
	[233] = "uk_vdso_syscall_epoll_ctl",
	[234] = "uk_vdso_syscall_tgkill",
	[235] = "uk_vdso_syscall_utimes",
	[236] = "uk_vdso_syscall_vserver",
	[237] = "uk_vdso_syscall_mbind",
	[238] = "uk_vdso_syscall_set_mempolicy",
	[239] = "uk_vdso_syscall_get_mempolicy",
	[240] = "uk_vdso_syscall_mq_open",
	[241] = "uk_vdso_syscall_mq_unlink",
	[242] = "uk_vdso_syscall_mq_timedsend",
	[243] = "uk_vdso_syscall_mq_timedreceive",
	[244] = "uk_vdso_syscall_mq_notify",
	[245] = "uk_vdso_syscall_mq_getsetattr",
	[246] = "uk_vdso_syscall_kexec_load",
	[247] = "uk_vdso_syscall_waitid",
	[248] = "uk_vdso_syscall_add_key",
	[249] = "uk_vdso_syscall_request_key",
	[250] = "uk_vdso_syscall_keyctl",
	[251] = "uk_vdso_syscall_ioprio_set",
	[252] = "uk_vdso_syscall_ioprio_get",
	[253] = "uk_vdso_syscall_inotify_init",
	[254] = "uk_vdso_syscall_inotify_add_watch",
	[255] = "uk_vdso_syscall_inotify_rm_watch",
	[256] = "uk_vdso_syscall_migrate_pages",
	[257] = "uk_vdso_syscall_openat",
	[258] = "uk_vdso_syscall_mkdirat",
	[259] = "uk_vdso_syscall_mknodat",
	[260] = "uk_vdso_syscall_fchownat",
	[261] = "uk_vdso_syscall_futimesat",
	[262] = "uk_vdso_syscall_newfstatat",
	[263] = "uk_vdso_syscall_unlinkat",
	[264] = "uk_vdso_syscall_renameat",
	[265] = "uk_vdso_syscall_linkat",
	[266] = "uk_vdso_syscall_symlinkat",
	[267] = "uk_vdso_syscall_readlinkat",
	[268] = "uk_vdso_syscall_fchmodat",
	[269] = "uk_vdso_syscall_faccessat",
	[270] = "uk_vdso_syscall_pselect6",
	[271] = "uk_vdso_syscall_ppoll",
	[272] = "uk_vdso_syscall_unshare",
	[273] = "uk_vdso_syscall_set_robust_list",
	[274] = "uk_vdso_syscall_get_robust_list",
	[275] = "uk_vdso_syscall_splice",
	[276] = "uk_vdso_syscall_tee",
	[277] = "uk_vdso_syscall_sync_file_range",
	[278] = "uk_vdso_syscall_vmsplice",
	[279] = "uk_vdso_syscall_move_pages",
	[280] = "uk_vdso_syscall_utimensat",
	[281] = "uk_vdso_syscall_epoll_pwait",
	[282] = "uk_vdso_syscall_signalfd",
	[283] = "uk_vdso_syscall_timerfd_create",
	[284] = "uk_vdso_syscall_eventfd",
	[285] = "uk_vdso_syscall_fallocate",
	[286] = "uk_vdso_syscall_timerfd_settime",
	[287] = "uk_vdso_syscall_timerfd_gettime",
	[288] = "uk_vdso_syscall_accept4",
	[289] = "uk_vdso_syscall_signalfd4",
	[290] = "uk_vdso_syscall_eventfd2",
	[291] = "uk_vdso_syscall_epoll_create1",
	[292] = "uk_vdso_syscall_dup3",
	[293] = "uk_vdso_syscall_pipe2",
	[294] = "uk_vdso_syscall_inotify_init1",
	[295] = "uk_vdso_syscall_preadv",
	[296] = "uk_vdso_syscall_pwritev",
	[297] = "uk_vdso_syscall_rt_tgsigqueueinfo",
	[298] = "uk_vdso_syscall_perf_event_open",
	[299] = "uk_vdso_syscall_recvmmsg",
	[300] = "uk_vdso_syscall_fanotify_init",
	[301] = "uk_vdso_syscall_fanotify_mark",
	[302] = "uk_vdso_syscall_prlimit64",
	[303] = "uk_vdso_syscall_name_to_handle_at",
	[304] = "uk_vdso_syscall_open_by_handle_at",
	[305] = "uk_vdso_syscall_clock_adjtime",
	[306] = "uk_vdso_syscall_syncfs",
	[307] = "uk_vdso_syscall_sendmmsg",
	[308] = "uk_vdso_syscall_setns",
	[309] = "uk_vdso_syscall_getcpu",
	[310] = "uk_vdso_syscall_process_vm_readv",
	[311] = "uk_vdso_syscall_process_vm_writev",
	[312] = "uk_vdso_syscall_kcmp",
	[313] = "uk_vdso_syscall_finit_module",
	[314] = "uk_vdso_syscall_sched_setattr",
	[315] = "uk_vdso_syscall_sched_getattr",
	[316] = "uk_vdso_syscall_renameat2",
	[317] = "uk_vdso_syscall_seccomp",
	[318] = "uk_vdso_syscall_getrandom",
	[319] = "uk_vdso_syscall_memfd_create",
	[320] = "uk_vdso_syscall_kexec_file_load",
	[321] = "uk_vdso_syscall_bpf",
	[322] = "uk_vdso_syscall_execveat",
	[323] = "uk_vdso_syscall_userfaultfd",
	[324] = "uk_vdso_syscall_membarrier",
	[325] = "uk_vdso_syscall_mlock2",
	[326] = "uk_vdso_syscall_copy_file_range",
	[327] = "uk_vdso_syscall_preadv2",
	[328] = "uk_vdso_syscall_pwritev2",
	[329] = "uk_vdso_syscall_pkey_mprotect",
	[330] = "uk_vdso_syscall_pkey_alloc",
	[331] = "uk_vdso_syscall_pkey_free",
	[332] = "uk_vdso_syscall_statx",
	[333] = "uk_vdso_syscall_io_pgetevents",
	[334] = "uk_vdso_syscall_rseq",
	[424] = "uk_vdso_syscall_pidfd_send_signal",
	[425] = "uk_vdso_syscall_io_uring_setup",
	[426] = "uk_vdso_syscall_io_uring_enter",
	[427] = "uk_vdso_syscall_io_uring_register",
	[428] = "uk_vdso_syscall_open_tree",
	[429] = "uk_vdso_syscall_move_mount",
	[430] = "uk_vdso_syscall_fsopen",
	[431] = "uk_vdso_syscall_fsconfig",
	[432] = "uk_vdso_syscall_fsmount",
	[433] = "uk_vdso_syscall_fspick",
	[434] = "uk_vdso_syscall_pidfd_open",
	[435] = "uk_vdso_syscall_clone3",
	[436] = "uk_vdso_syscall_close_range",
	[437] = "uk_vdso_syscall_openat2",
	[438] = "uk_vdso_syscall_pidfd_getfd",
	[439] = "uk_vdso_syscall_faccessat2",
	[440] = "uk_vdso_syscall_process_madvise",
	[441] = "uk_vdso_syscall_epoll_pwait2",
	[442] = "uk_vdso_syscall_mount_setattr",
	[444] = "uk_vdso_syscall_landlock_create_ruleset",
	[445] = "uk_vdso_syscall_landlock_add_rule",
	[446] = "uk_vdso_syscall_landlock_restrict_self"
};

void uk_init_vdso_syscall_tabel(void) __attribute__((constructor));

void uk_init_vdso_syscall_tabel(void) {
	for (int i = 0; i < UK_VDSO_SYSCALL_MAX; i++) {
		if (uk_vdso_syscall_name[i]) {
			uk_vdso_syscall_tabel[i] = __vdsosym("LINUX_2.6", uk_vdso_syscall_name[i]);
			if (uk_vdso_syscall_tabel[i]) {
				printf("Found symbol in VDSO: %s\n", uk_vdso_syscall_name[i]);
			}
		}
	}
}

long __uk_syscall_0(long syscall_nr) {
	return uk_vdso_syscall_tabel[syscall_nr]? (((long(*)())uk_vdso_syscall_tabel[syscall_nr])()) : (___syscall(syscall_nr));
}

long __uk_syscall_1(long syscall_nr, long a) {
	return uk_vdso_syscall_tabel[syscall_nr]? (((long(*)(long))uk_vdso_syscall_tabel[syscall_nr])(a)) : (___syscall(syscall_nr, a));
}

long __uk_syscall_2(long syscall_nr, long a, long b) {
	return uk_vdso_syscall_tabel[syscall_nr]? (((long(*)(long, long))uk_vdso_syscall_tabel[syscall_nr])(a, b)) : (___syscall(syscall_nr, a, b));
}

long __uk_syscall_3(long syscall_nr, long a, long b, long c) {
	return uk_vdso_syscall_tabel[syscall_nr]? (((long(*)(long, long, long))uk_vdso_syscall_tabel[syscall_nr])(a, b, c)) : (___syscall(syscall_nr, a, b, c));
}

long __uk_syscall_4(long syscall_nr, long a, long b, long c, long d) {
	return uk_vdso_syscall_tabel[syscall_nr]? (((long(*)(long, long, long, long))uk_vdso_syscall_tabel[syscall_nr])(a, b, c, d)) : (___syscall(syscall_nr, a, b, c, d));
}

long __uk_syscall_5(long syscall_nr, long a, long b, long c, long d, long e) {
	return uk_vdso_syscall_tabel[syscall_nr]? (((long(*)(long, long, long, long, long))uk_vdso_syscall_tabel[syscall_nr])(a, b, c, d, e)) : (___syscall(syscall_nr, a, b, c, d, e));
}

long __uk_syscall_6(long syscall_nr, long a, long b, long c, long d, long e, long f) {
	return uk_vdso_syscall_tabel[syscall_nr]? (((long(*)(long, long, long, long, long, long))uk_vdso_syscall_tabel[syscall_nr])(a, b, c, d, e, f)) : (___syscall(syscall_nr, a, b, c, d, e, f));
}
